In [0]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[-2.16061042 -1.22750439 -0.88162225 -0.81479975  0.41721122]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-2.16061042 -1.22750439 -0.88162225 -0.81479975  0.41721122]


In [5]:
print(np.dot(a,a.T))

7.790226031994465


In [6]:
b = np.random.randn(5,1)
print(b)

[[ 1.77807468]
 [ 1.50143835]
 [ 0.09743557]
 [-0.62017292]
 [ 0.68135109]]


In [7]:
print(b.T)

[[ 1.77807468  1.50143835  0.09743557 -0.62017292  0.68135109]]


In [8]:
print(np.dot(b,b.T))

[[ 3.16154957  2.66966951  0.17324771 -1.10271377  1.21149312]
 [ 2.66966951  2.25431712  0.1462935  -0.93115141  1.02300665]
 [ 0.17324771  0.1462935   0.00949369 -0.0604269   0.06638783]
 [-1.10271377 -0.93115141 -0.0604269   0.38461445 -0.42255549]
 [ 1.21149312  1.02300665  0.06638783 -0.42255549  0.46423931]]


In [9]:
assert(a.shape == (5,1))

AssertionError: ignored

In [0]:
assert(b.shape == (5,1))